### ISSUE TITLE
Selector switch doesn't work

### ISSUE THREAD

**Issue by Martijn085** [Dashticz/dashticz_v2#249]
In my config.js i have this option:

`config['selector_instead_of_buttons'] = 1`;

But the toon profiles switch still keeps showing buttons instead of a selector switch.

![afbeelding](https://user-images.githubusercontent.com/1752627/34747264-bdb27be8-f597-11e7-9455-56d71cc72ee8.png)

**Comment by aalwash** [comment]
Somehow the code that does this, is removed
Not sure why?  @robgeerts maybe knows?

It was implemented in july 2017 https://github.com/Dashticz/dashticz_v2/commit/7962a664ded5c8600ffe9cbe5c3f4ec57c3571c7

**Comment by aiolos** [comment]
Hmm, I might have accidentally removed it in the big refactor (I didn't even know it existed...). I will have a look later to compare with master.

**Comment by aiolos** [comment]
It wasn't me: https://github.com/Dashticz/dashticz_v2/commit/daf74e8fa1380aa1ca60a0441a2afd4bea446737

But the functionality is still there: In domoticz you can set the selector style. If you change that, dashticz will also change. You can find the setting when you edit a device in domoticz.

**Comment by Martijn085** [comment]
The switch has in Domoticz already the selecter style. The switch in Dashticz still has the buttons style..

![2018_02_02_15_05_32_domoticz](https://user-images.githubusercontent.com/1752627/35737143-d08ace78-082a-11e8-8ce0-60861338b9a8.png)

**Comment by htilburgs** [comment]
This issue is still there.
Also the related option config['hide_off_button'] doesn't work.
Doesn't matter what you select in Domoticz, this setting is not correct (it always shows the OFF button).

**Comment by aalwash** [comment]
@htilburgs if you want to disable the off button, you go to the Switch itself (in Domoticz) and enable 'Hide off level'

**Comment by DewGew** [comment]
Still an issue?

**Comment by Martijn085** [comment]
Yes, still like the first picture i posted.

**Comment by DewGew** [comment]
Try this in your config config['selector_instead_of_buttons'] = 1;

**Comment by Martijn085** [comment]
As you can see in my first post i already use: config['selector_instead_of_buttons'] = 1;  and also check the 6th post, there i hava set the style to selecter.

Last year (dec 2017) this worked fine, but somewhere in the beginning of this year (2018) there has been some changes that causes this.

**Comment by DewGew** [comment]
Have changed this setting?
![37edbc80-cbf9-4c9d-a247-56cdd6dbdc04](https://user-images.githubusercontent.com/28799807/41330992-df944f1c-6ed6-11e8-9d55-0fb28368b524.jpeg)

**Comment by Martijn085** [comment]
I only saw the switch type and mist this option. This one did the trick, thanks!
