### ISSUE TITLE
Spotify issue

### ISSUE THREAD

**Issue by Miloune** [Dashticz/dashticz_v2#256]
Hello,

It's an already know bug, but i didn't see any issue open on Github. It's easier to track the change when you will do it.
Can you let open this issue while the problem is not fixed please ? So when we got notification we can enable again Spotify module.

Here is the forum post i found: https://www.domoticz.com/forum/viewtopic.php?f=67&t=18280&start=60

**Comment by aalwash** [comment]
I've fixed the issue and did a PR

So soon it should be in the beta branch

**Comment by Tontze** [comment]
should it be config['spot_clientid'] = '1112f16564cf4f4d93ccbe8b52c58a44';

instead of wiki module page:

settings['spot_clientid'] = '1112f16564cf4f4d93ccbe8b52c58a44';

**Comment by aalwash** [comment]
I don't see the difference?

**Comment by aalwash** [comment]
Thanks for noticing, I changed it to config
