### ISSUE TITLE
Hide data options doesn't work (anymore) for Blinds

### ISSUE THREAD

**Issue by htilburgs** [Dashticz/dashticz_v2#265]
Option `blocks[x]['hide_data'] = true; `doesn't work (anymore) for Blinds.

**Comment by DewGew** [comment]
Hide data on blinds is works on blinds percentage to switch between level eg. "50%" or Open/Close.
I can add hide "open/close" on blinds without percentage if its that you are refering to?

**Comment by DewGew** [comment]
Hide data on blinds is works on blinds percentage to hide between level.
![blind](https://user-images.githubusercontent.com/28799807/36023189-e6053e6c-0d8b-11e8-995a-1cc45af76728.jpg)

I can add hide "open/close" on blinds
![blind 2](https://user-images.githubusercontent.com/28799807/36023211-f99ea0ee-0d8b-11e8-8efe-82d6a53e7b99.jpg)

**Comment by DewGew** [comment]
Added in #270

**Comment by DewGew** [comment]
Issue is fixed. Close this one..
