### ISSUE TITLE
getIconStatusClass crashes - deviceStatus == undefined

### ISSUE THREAD

**Issue by QuantumSingularity** [Dashticz/dashticz_v2#280]
In my network deviceStatus == undefined.
I've fixed it, but I cannot push.
(I'm using pi.hole. I've seen dashticz tries to connect to Google Analytics. Maybe it's related.)

Branch Beta, main.js, line 1480:

function getIconStatusClass(deviceStatus) {
    if (deviceStatus != undefined)
    {    
        switch (deviceStatus.toLowerCase()) {
            case 'off':
            case 'closed':
            case 'normal':
                return 'off';
        }
        return 'on';
    }
    else
    {
        return "off";
    }        
}

**Comment by DewGew** [comment]
Merged #282
