### ISSUE TITLE
Some items keep loading (in Windows, iOS)

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz_v2#284]
Google agenda, publictransport and tv guide keeps loading in my Dashticz dashboard.
I did a clean install of the latest beta and used the default config.js. Even then I have problems with loading the items publictransport and tvguide. The strange thing is I don't have problems when running in Ubuntu Linux.
My old version from august (was running fine for months) but has same loading problems now.

**Comment by Tontze** [comment]
I have same issue with my calendar.

**Comment by DewGew** [comment]
@robgeerts and @aiolos you are needed

**Comment by aiolos** [comment]
What exactly keeps loading? And do the developer tools give any insight? (like failing requests) 
It sounds more like something has changed with these calendars or the loading of external data. (given that an old version suddenly stops working)

Which browsers do have this problem? Does a change of the browser solve the problem?

**Comment by Tontze** [comment]
Oh, and if i click calendar(where reeads only loading...) it actually downloads correct calendar .ics

**Comment by robgeerts** [comment]
Weird, just tested on my windows pc on chrome. Works fine.. The error you mention you get in console has nothing to do with this ;) Could you check the network tab for any red-colored requests?

**Comment by Timme001** [comment]
Same issue as reported by Tontze.  Network tab does not show any red colored requests. When filtering on ical in network tab I see request to https://wedevise.nl/dashticz/ical/?time=1521500050665&url=https://calendar.google.com/calendar/ical/ti........................

The Ical URL itself works as it download an .ics file

**Comment by Tontze** [comment]
In beta it worked, but today chrom console : 

2dashticz.nl/ical/?time=1522692868423&url=https://www.hobbydeed.com/api/v2/public/calendar-share/fi/user/-s5895b91c4e2be4.56780603/file/all.ics Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Failed to load http://dashticz.nl/ical/?time=1522692868423&url=https://www.hobbydeed.com/api/v2/public/calendar-share/fi/user/-s5895b91c4e2be4.56780603/file/all.ics: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.8.150:8080' is therefore not allowed access. The response had HTTP status code 404.
