### ISSUE TITLE
show last update (with default setting) not working

### ISSUE THREAD

**Issue by tsybeck** [Dashticz/dashticz_v2#286]
Hi, 

Wanted to say I really like your Dashticz project! :)
But I found a minor bug today.

I recently started a new dashticz installation and want to keep the configuration file as clean as possible.
So I only add parameters where I need to.

When I tried to add a block and hide the 'last update', I added the line for 'show_lastupdate' to my block. See below.

blocks[156] = {}
blocks[156]['width'] = 4; 
blocks[156]['title'] = 'Electriciteit'
blocks[156]['show_lastupdate'] = false;

This did nothing, updates where still shown.

When I added the main config-parameter (config['last_update'] = 0;), all updates were hidden. Now I can show updates for a single block with 'show_lastupdate = true'.

But it should work when I dont define the main config-parameter (then default is that last_updates are shown) and I declare 'show_update = false' for a single block

**Comment by ramonleenders** [comment]
For blocks it should be **hide_lastupdate** instead - don't ask me why though. It's just not documented I guess, since the docs here:

https://www.domoticz.com/wiki/Dashticz_V2_-_Positioning

Say it's show_lastupdate

**Comment by aiolos** [comment]
The referenced PR is solving this issue, in the `blocks`-config you now need to configure this as
`blocks[156]['last_update'] = false;`
