### ISSUE TITLE
Mixed content is blocked in Firefox 

### ISSUE THREAD

**Issue by ericvb** [Dashticz/dashticz_v2#311]
My Dashticz website is running under https.
Accessing http content is blocked, see https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
For example the ov bus information will not work : Blocked loading mixed active content “http://dashticz.nl/ov/ov.php?station=son-en-breugel/bushalte-penseelkever&time=1525182736388”
If I configure the VVS information, it is working because the link is also https.

It is related to the issue Security Problem #276

**Comment by robgeerts** [comment]
Is fixed in latest beta!
