### ISSUE TITLE
Adding public transport for NMBS Belgium

### ISSUE THREAD

**Issue by ericvb** [Dashticz/dashticz_v2#312]
I've added some code to the publictransport.js file to support also the public transport NMBS for Belgium.
I don't have GIT installed on my home machine, so I can't do a pull request.
CONFIG.js
`publictransport.nmbs={station:'Mol',title:'Station Mol',show_lastupdate:true,provider:'irailbe',icon:'train',interval:15,width:7,results:5};`
Add the created publictransport.nmbs object to the columns in your Dashticz design.
(via the irail.be website you can figure out what the name is of your station)

Replace the existing publictransport.js by the new one: 
[publictransport.zip](https://github.com/Dashticz/dashticz_v2/files/1964996/publictransport.zip)

I'm not using the realtime 'open' data directly from the NMBS site, because for them it is not really 'open' data (http://www.belgianrail.be/nl/klantendienst/faq/public-data.aspx), so I did take the data from the irail.be website.

**Comment by robgeerts** [comment]
Thanks, added to beta!
