### ISSUE TITLE
Adding also public transport for DeLijn bussen Belgium

### ISSUE THREAD

**Issue by ericvb** [Dashticz/dashticz_v2#313]
Did the same as for the NMBS.
CONFIG.js
publictransport.delijnMol = {station: '109991+406796+406795+406792+107606+107604+107605', title: 'Bus station Mol', show_lastupdate:true, provider: 'delijnbe', icon: 'bus', interval: 15, width: 4, results: 10 };
Via the website delijn.be (https://www.delijn.be/nl/zakelijk-aanbod/reisinfo-op-maat/gebruikershandleiding-realtime-haltescherm.html) you can get the numbers of the stops you want to see. Encode them like above with a + sign.

[publictransport.zip](https://github.com/Dashticz/dashticz_v2/files/1968619/publictransport.zip)
This file has the complete code for the NMBS and DeLijn.

Example screen:
![2018-05-02 21_37_34-dashticz](https://user-images.githubusercontent.com/3419875/39545513-b2a4c702-4e51-11e8-8158-11bca0ce1350.png)

**Comment by robgeerts** [comment]
Added to BETA!
Thanks for you additions!
