### ISSUE TITLE
Representation of Humidity Sensor

### ISSUE THREAD

**Issue by czacha338** [Dashticz/dashticz_v2#337]
Hello,

First of all I would like to thank you for perfect dashboard. It's much better for HMI then normal one :)

I have found some bug related to building blocks for Humidity sensor. When in domoticz there is defined sensor only with Humidity sensor it is build twice (one with temperature icon and one with humidity). 
![block_humidity](https://user-images.githubusercontent.com/40031567/41195149-a75bdb02-6c28-11e8-89dc-731162b8a150.PNG)

The problem is laying in main.js file, funtion **getTempHumBarBlock(device, idx)**

I have corrected it by creating a new function called **getHumBlock(device, idx);** and changing the switch **switch (device['Type'])**

My changes are below, if you would like you can marge them to you branch. :)

```
git diff main.js
diff --git a/js/main.js b/js/main.js
index d5f088b..876ddb0 100644
--- a/js/main.js
+++ b/js/main.js
     switch (device['Type']) {
+      case 'Humidity':
+             return getHumBlock(device, idx);
         case 'Temp + Humidity + Baro':
         case 'Temp + Humidity':
-        case 'Humidity':

+function getHumBlock(device, idx) {
+    this.html = '';
+       var blockValues = [
+        {
+            icon: 'wi wi-humidity',
+            idx: idx,
+            title: device['Name'],
+            value: number_format(device['Humidity'], 0),
+            unit: '%'
+        },
+    ];
+       createBlocks(blockValues, device);
+    return ['', false];
+}
```

After this change, when sensor has only Humidity defined is represented as one block:

![block_humidity_ok](https://user-images.githubusercontent.com/40031567/41195265-185c466a-6c2a-11e8-8bee-614b931fe471.PNG)

Best regards,

Adrian

**Comment by DewGew** [comment]
I suggest you make a pull reguest

**Comment by lokonli** [comment]
I've created the pull request for this.

**Comment by robgeerts** [comment]
Merged! :) Thanks!

**Comment by czacha338** [comment]
Your welcome :)
