### ISSUE TITLE
Fontawesome v5.0.13

### ISSUE THREAD

**Issue by DewGew** [Dashticz/dashticz_v2#338]
I updated to fontawsome v5.0.13. But I I had to change the icon handling in most files. I think dashticz look better with new fontawsome. I suggest to update fontawsome.... 
Its need to change the icon names  from fa-icon to fas fa-icon or far fa-icon (depending what icon you want) in CONFIG.js

![dashticz](https://user-images.githubusercontent.com/28799807/41279783-aef3abd6-6e2d-11e8-95a7-017e1b22521f.png)

**Comment by lokonli** [comment]
I've tested it. After renaming the icons in CONFIG.js I see them, but they are very small. Previously they were  enlarged for big screen sizes.

**Comment by lokonli** [comment]
The style modifiers for .far in creative.css are missing. (.fa still is in)

**Comment by DewGew** [comment]
Oh yes, I forgot the css files....

**Comment by DewGew** [comment]
I updated the CSS file..

**Comment by jvalst** [comment]
Will this be merged into the beta of Dashticz?
