### ISSUE TITLE
Understanding structure Dashticz

### ISSUE THREAD

**Issue by RiLaSol** [Dashticz/dashticz_v2#361]
Hi Dashticz developer(s),
I like the idea about Dashticz but I have a bit of a problem to understand the structure.
I will give two examples.

If I want to show TV stations I need to tell which channels, of course, but were can I find the number of the channels I desire?
The numbers in:
 tvguide.dutch = { key:'dutch', icon: 'fa-television', width:7, channels: [1,2,3,4,5,6,7,8,9,31,46,92], maxitems: 5 }
represent which stations?

Also with bus stations, I need to tell the name of the local busstation. In the standard that is a station in son en breugel, but where can I find the exact name of my local busstation.
publictransport.ovinfobus = { show_via: false, station: '...', provider: '9292-bus', icon: 'bus', width:5, results: 6 }
What to put on the dots in above line?

This kind of answers to the structure I don't know were to find. Who can help?

Thank you in advance.

**Comment by robgeerts** [comment]
For Tv Guide, open this url: http://dashticz.nl/tv/channels.php
Copy text into the textarea on this website so you can actually read: http://json.parser.online.fr/

About the bus stations, wich one is your station?
