### ISSUE TITLE
Colour picker not working in Beta Branch

### ISSUE THREAD

**Issue by SaintLenneth** [Dashticz/dashticz_v2#364]
Hi everyone,

Have moved on to Beta Branch which solved a Button/Selector Switch issue detailed here [https://github.com/Dashticz/dashticz_v2/issues/359](url)

But after moving there, I found that the colour picker does not appear for coloured lights. 
![image](https://user-images.githubusercontent.com/41514839/44305264-06df5b80-a3a6-11e8-85e4-8664ec03a8af.png)

But it was working fine in the master branch.
Not sure if I have done anything wrong and will appreciate any advise.

Thank you !

**Comment by lokonli** [comment]
Did you try the following setting in your CONFIG.js:
`config['no_rgb'] = 0;`

**Comment by SaintLenneth** [comment]
Hi lokonli, that did the trick ! 
Thanks ! =D
