### ISSUE TITLE
Spotify messes up layout

### ISSUE THREAD

**Issue by rldn21** [Dashticz/dashticz_v2#365]
Hi all, 

I know there is a bug in the master version of dashticz which messes up the layout of dashticz when adding the spotify plugin. I run v. 2.3.3 master and want to know when or how the bug will be fixed? 

Or how can i update from master to beta without losing all data and settings?
Please give me a solution. (PS1: the "double check path error" of mine is still not fixed, see other topic). 

PS2: super duper work rob! Love the dash!

**Comment by lokonli** [comment]
You can try beta next to the master version.
Go to the parent folder of your dashticz folder.
then
`git clone -b beta https://github.com/Dashticz/dashticz_v2.git dtb`

(dtb is name of the new folder with the beta branch)

Copy your CONFIG.js (and if needed your custom.css and custom.js) from the dashticz/custom folder to dtb/custom

Dashticz-beta is the accessible via http://<domoticz:port>/dtb/
