### ISSUE TITLE
Trash icon now on top instead left

### ISSUE THREAD

**Issue by saschaabraham** [Dashticz/dashticz_v2#376]
With version 2.4 the trash icon in the garbage module is now located on top of the collecting dates.
Now the module need more vertikal space. In the version before the icon was placed left from the dates. This looked better with less space needed.

**Comment by MSe-5-14** [comment]
@robgeerts you can close this issue.

**Comment by saschaabraham** [comment]
Cloned the beta today (2018-10-06) and the icon is on the right position.
