### ISSUE TITLE
Calendar not loading

### ISSUE THREAD

**Issue by Martijnh89** [Dashticz/dashticz_v2#403]
Hi!

Since the last beta and master updates the calendar is not loading, it keeps saying "Loading..". I haven't changed anything in the config, just updating Dashticz. I tried to use one calendar instead of a combined one, different sources and also something I found earlier about adding 
https://cors-anywhere.herokuapp.com/, but without any luck.

Hope it helps to find and fix a bug!

**Comment by lokonli** [comment]
Please check the following thread:
[https://www.domoticz.com/forum/viewtopic.php?f=67&t=24907&sid=9c7e25edecf770b53624f6a97bc6e892]

Summarizing: Install Apache (with PHP enabled) and install the latest beta.

For calendar there should be no need to use cors-anywhere.
If you still have issues, then please open a topic on the dashticz forum:
https://www.domoticz.com/forum/viewforum.php?f=67

**Comment by Martijnh89** [comment]
Thanks! That makes sense, sorry for not checking that first.
