### ISSUE TITLE
OpenWeatherMap in Dashticz

### ISSUE THREAD

**Issue by turboproc** [Dashticz/dashticz_v2#406]
After reading the message that WU is not providing new API keys anymore, I decided to walk the OWM path and started to modify weather.js until it works with OWM. Not perfect jet but the basic are there. Was just wondering weather I'm working on something that has been done already or whether I should contribute the result.

**Comment by lokonli** [comment]
OWM has been implemented already in the beta release.
See:
https://www.domoticz.com/forum/viewtopic.php?f=67&t=24073#p185427

**Comment by aalwash** [comment]
If add this in the configuration, you will see days
`config['owm_days'] = 4;`

And use
`weather_owm` as a block, you should see 4 days
