### ISSUE TITLE
Alot of settings in CONFIG.js

### ISSUE THREAD

**Issue by DewGew** [Dashticz/dashticz_v2#420]
There are alot of settings in CONFIG.js (config variable). Not all is in the settings menu. Is it possible to add all those to settings menu?

**Comment by lokonli** [comment]
Yes (at least, most of them) :)
Which are missing?

**Comment by HansieNL** [comment]
config['longfonds_zipcode'] = '5654SB';
config['longfonds_housenumber'] = '3';

**Comment by lokonli** [comment]
Longfonds has been added in the last beta.
It seems hide_off_button is not used in the code. Is it working?
I will add the two standby settings.
